export const STORE_FETCHED_PAGES = 'STORE_FETCHED_PAGES';
export const PAGES_LOADED = 'PAGES_LOADED';

export const STORE_FETCHED_POSTS = 'STORE_FETCHED_POSTS';
export const POSTS_LOADED = 'POSTS_LOADED';

export const STORE_FETCHED_PRODUCTS = 'STORE_FETCHED_PRODUCTS';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';

export const STORE_FETCHED_SINGLE_PRODUCT = 'STORE_FETCHED_SINGLE_PRODUCT';
export const PRODUCT_SINGLE_LOADED = 'PRODUCT_SINGLE_LOADED';
export const RESET_STATE_PRODUCT = 'RESET_STATE_PRODUCT';

export const CART_LOADED = 'CART_LOADED';
export const STORE_CART_PRODUCTS = 'STORE_CART_PRODUCTS';
export const STORE_CART_CLEAR = 'STORE_CART_CLEAR';
export const STORE_CART_REMOVE = 'STORE_CART_REMOVE';
export const STORE_CART_TOTAL  = 'STORE_CART_TOTAL';

export const CHECKOUT_LOADED = 'CHECKOUT_LOADED';



// export const STORE_FETCHED_USER = 'STORE_FETCHED_USER';
// export const LOGIN_USER = 'LOGIN_USER';
// export const LOGOUT_USER = 'LOGOUT_USER';
//
// export const STORE_FETCHED_CATEGORIES = 'STORE_FETCHED_CATEGORIES';
// export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';